### ISSUE TITLE
Readme clarification

### ISSUE THREAD

**Issue by HermanGonzalez** [LoremIpsumGraz/mocking-hans#1]
When I tried the start command in the readme file I get basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')") error.

I can work directly with the hans command but trying "start": "ts-node-dev ./node_modules/.bin/hans apps --disable-compilation" produce the error

env
Powershell 5.1

**Comment by nehalist** [comment]
After some research it seems like this a Windows-exclusive issue. The easiest way to fix it is to change the command accordingly:

```
"start": "ts-node-dev ./node_modules/@loremipsum/mocking-hans/dist/console.js apps --disable-compilation"
```

**Comment by HermanGonzalez** [comment]
Thanks for the help and clarification, it would be nice if this could be found in the readme file for future cases, but overall thanks.
